server.port=8082
spring.application.name=notification-service

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# SendGrid (Render) + Gmail (Local) Dual Config
spring.mail.host=${SPRING_MAIL_HOST:smtp.sendgrid.net}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:${SPRING_MAIL_USERNAME}}
spring.mail.password=${MAIL_PASSWORD:${SPRING_MAIL_PASSWORD}}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.sendgrid.net

logging.level.com.sun.mail.smtp=DEBUG
logging.level.com.healthcare.notificationservice=DEBUG