server.port=${PORT:8081}
spring.application.name=appointment-service

# H2 In-Memory Database (Render)
spring.datasource.url=jdbc:h2:mem:appointmentsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Disable RabbitMQ (notification-service handles this)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

# JWT (Render Environment Variable)
jwt.secret=${JWT_SECRET}
jwt.expiration=900000

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html